### ISSUE TITLE
TypeError: apply_overlay() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by GoldenDarkness55** [Metachs/sdwebui-nai-api#10]
Getting the error in the title when trying to "inpaint only masked" on the new FORGE UI. Im aware this was made for AUTO but because it's deprecated now with everyone switching over and the UIs are very similar I'd love a fix. Seems to work fine otherwise.

Console log
Traceback (most recent call last):
      File "F:\stable diffusion\FORGE\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\stable diffusion\FORGE\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\stable diffusion\FORGE\webui\modules\img2img.py", line 235, in img2img
        processed = process_images(p)
      File "F:\stable diffusion\FORGE\webui\modules\processing.py", line 749, in process_images
        res = process_images_inner(p)
      File "F:\stable diffusion\FORGE\webui\extensions\sdwebui-nai-api\nai_api_gen\nai_api_processing.py", line 115, in process_images_patched
        results = modules.processing.process_images_pre_patch_4_nai(p)
      File "F:\stable diffusion\FORGE\webui\modules\processing.py", line 813, in process_images_inner
        p.scripts.process(p)
      File "F:\stable diffusion\FORGE\webui\extensions\sdwebui-nai-api\nai_api_gen\nai_api_processing.py", line 107, in process_patched
        script.nai_image_processsing(p, *args) # Sets p.nai_processed if images have been processed
      File "F:\stable diffusion\FORGE\webui\extensions\sdwebui-nai-api\nai_api_gen\nai_api_script.py", line 421, in nai_image_processsing
        if not self.use_batch_processing: self.nai_generate_images(p, *args, **kwargs)
      File "F:\stable diffusion\FORGE\webui\extensions\sdwebui-nai-api\nai_api_gen\nai_api_script.py", line 490, in nai_generate_images
        self.get_batch_images(p, getparams, save_images = isimg2img and getattr(p,"inpaint_full_res",False) and shared.opts.data.get('nai_api_save_fragments', False), save_suffix ="-nai-init-image" if do_local_img2img > 0 else "" ,overlay = inpaint_mode == 1 or getattr(p,"inpaint_full_res",False))
      File "F:\stable diffusion\FORGE\webui\extensions\sdwebui-nai-api\nai_api_gen\nai_api_script.py", line 605, in get_batch_images
        image = apply_overlay(self.images[i],  (self.crop[0], self.crop[1], self.crop[2]-self.crop[0], self.crop[3]-self.crop[1]), 0, self.init_masked)
    TypeError: apply_overlay() takes 3 positional arguments but 4 were given

**Comment by Metachs** [comment]
No idea what FORGE is, but the same issue occurs with the A1111 dev branch, just added a fix for it which should resolve this issue

**Comment by GoldenDarkness55** [comment]
its quite literally just auto but better cause it has newest optimizations https://github.com/lllyasviel/stable-diffusion-webui-forge
Thanks anyways
