### ISSUE TITLE
read_info_from_image_stealth: NameError

### ISSUE THREAD

**Issue by Chololoco13** [Metachs/sdwebui-nai-api#25]
read_info_from_image_stealth: NameError
Traceback (most recent call last):
  File "C:\Users\H9\OneDrive\Documentos\IA\Version Limpia 19-3\stable-diffusion-webui\extensions\sdwebui-nai-api\nai_api_gen\nai_stealth_text_info.py", line 420, in read_info_from_image_stealth
    return process_nai_geninfo(items)
  File "C:\Users\H9\OneDrive\Documentos\IA\Version Limpia 19-3\stable-diffusion-webui\extensions\sdwebui-nai-api\nai_api_gen\nai_stealth_text_info.py", line 164, in process_nai_geninfo
    if math.abs(get_skip_cfg_above_sigma(tryfloat(j["width"]), tryfloat(j["height"]))) < epsilon:
NameError: name 'math' is not defined

I updated to the latest version and when I want to analyze images in the PNG INFO option I get the following error.
Thanks for the updates and your work.

**Comment by Chololoco13** [comment]
I think this error only happens with the images that were generated with the Variety+ option, the rest of the images that were generated without Variety+ can be analyzed without errors.

**Comment by Chololoco13** [comment]
oh I closed it by mistake.

**Comment by Metachs** [comment]
Thanks, should be fixed.
