### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by hdroller** [Metachs/sdwebui-nai-api#9]
Hello, I'm getting the following error when I try to generate an image. The weird thing is I don't even have it enabled. Any suggestions on how to fix this? I would provide recreation steps but I can't consistently recreate it. The other odd thing, is when I run into this, I can usually gen on other tabs and then eventually I'll go back to the broken tab and it will start working again.

Traceback (most recent call last):
  File "E:\AutoXL\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AutoXL\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\AutoXL\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\AutoXL\stable-diffusion-webui\extensions\sdwebui-nai-api\nai_api_gen\nai_stealth_text_info.py", line 398, in custom_image_preprocess
    assert isinstance(x, dict)
AssertionError

**Comment by Metachs** [comment]
No idea what is going on there, that code came from the stealth PNG extension and as far as I can tell it never really worked, and would have caused problems if it did, and it was causing another minor issue, so I removed it. Should most likely fix this issue as well.
